language: python
sudo: false
cache: pip
python:
  - 3.6
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5 pypy
env:
  - TOXENV=py27-pytest30-supported-xdist
  - TOXENV=py27-pytest31-supported-xdist
  - TOXENV=py27-pytest34-supported-xdist
  - TOXENV=py27-pytest30-unsupported-xdist
  - TOXENV=py34-pytest30-supported-xdist
  - TOXENV=py34-pytest31-supported-xdist
  - TOXENV=py34-pytest34-supported-xdist
  - TOXENV=py35-pytest30-supported-xdist
  - TOXENV=py35-pytest34-supported-xdist
  - TOXENV=py36-pytest30-supported-xdist
  - TOXENV=py36-pytest34-supported-xdist
  - TOXENV=py35-pytest30-unsupported-xdist
  - TOXENV=py37-pytest37-supported-xdist
  - TOXENV=pypy-pytest30-supported-xdist
  - TOXENV=pypy-pytest31-supported-xdist
install: pip install -U tox
script:
  - tox
